version: "3.8"

services: 
  nginx:
    image: nginx
    container_name: mf_nginx
    ports: 
      - "3200:80"
    environment: 
      NGINX_PORT: 80
    volumes: 
      - "./client/nginx.conf:/etc/nginx/nginx.conf"
      - "./client/dist/client:/etc/nginx/html"
    networks: 
      - frontend
    
  api:
    container_name: mf_api
    build: ./server
    depends_on: 
      - mongodb
    ports:
      - "3201:3000"
    volumes: 
      - "./server:/app"
    networks: 
      - backend
      - frontend
  
  mongodb:
    container_name: mf_mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: 
      - backend
    volumes: 
      - mwafinalmongodata:/data/db

  mongo-express:
    image: mongo-express
    container_name: mf_mongo-express
    env_file: 
      - .docker-compose.env
    networks: 
      - backend
    ports: 
      - "8090:8081"
    depends_on: 
      - mongodb
    

networks: 
  frontend:
  backend:

volumes: 
  mwafinalmongodata:
    